let translations = {
    Uz: {
        nav_item1: "Uyga",
        nav_item2: "Portfel",
        nav_item3: "Blog",
        nav_item4: "Sahifalar",
        nav_item5: "Bog'lanish",
        animation1_1: "Bizdan",
        animation1_2: "doimo",
        animation1_3: "eng",
        animation1_4: "so'nggi",
        animation1_5: "modellarni",
        big_contain: "Qulay narxlar",
        animation2_1: "qulay",
        animation2_2: "va arzon",
        animation2_3: "narxlarda",
        animation2_4: "topishingiz",
        animation2_5: "mumkin",
        center1_1: "Quyidagilarni",
        center1_2: "bizdan",
        center1_3: "xarid",
        center1_4: "qilishingiz",
        center1_5: "mumkin",
        "card-title1": "GOODTECH kompressor",
        "card-text1": "Brend: GOODTECH",
        button1: "Yaqinroq",
        "card-title-modal1": "GOODTECH kompressor",
        "card-text-modal1": "Brend: GOODTECH",
        modal_nested1 : "Brend",
        modal_nested1_1 : "mamlakati:",
        modal_nested1_2 : "Xitoy,",
        modal_nested2 : "Voltaj:",
        modal_nested2_1 : "220 V,",
        modal_nested2_1V : "380 V",
        modal_nested3 : "Tarmoq",
        modal_nested3_1 : "chastotasi: 50 Hz,",
        modal_nested4 : "Oqim:",
        modal_nested4_1 : "13.5 A,",
        modal_nested4_1A : "6.5 A",
        modal_nested4_1A_1 : "8.2 A",
        modal_nested4_1A_2 : "11 A",
        modal_nested5 : "Quvvat:",
        modal_nested5_1 : "2.2 kV,",
        modal_nested5_1W : "3 kV",
        modal_nested5_1W_1 : "4 kV",
        modal_nested5_1W_2 : "5.5 kV",
        modal_nested6 : "Aylanish",
        modal_nested6_1 : "tezligi:",
        modal_nested6_2 : "1050r/min,",
        modal_nested6_2T : "950r/min,",
        modal_nested7 : "Ish bosimi:",
        modal_nested7_1 : "0.8MPa,",
        modal_nested8 : "Hosildorlik:",
        modal_nested8_1 : "0.25 m3/min,",
        modal_nested8_1H : "0.36 m3/min,",
        modal_nested8_1H_1 : "0.6 m3/min,",
        modal_nested8_1H_2 : "0.67 m3/min,",
        modal_nested9 : "Silindr:",
        modal_nested9_1 : "65x2,",
        modal_nested9_1B : "65x3,",
        modal_nested9_1B_1 : "90x2,",
        modal_nested9_1B_2 : "80x2,",
        modal_nested10 : "Tank hajmi:",
        modal_nested10_1 : "90 l.",
        modal_nested10_1L : "150 l.",
        modal_nested10_1L_1 : "180 l.",
        "card-title2": "GOODTECH kompressor",
        "card-text2": "Brend: GOODTECH",
        button2: "Yaqinroq",
        "card-title-modal2": "GOODTECH kompressor",
        "card-text-modal2": "Brend: GOODTECH",
        "card-title3": "GOODTECH kompressor",
        "card-text3": "Brend: GOODTECH",
        button3: "Yaqinroq",
        "card-title-modal3": "GOODTECH kompressor",
        "card-text-modal3": "Brend: GOODTECH",
        "card-title6-2": "GOODTECH kompressor",
        "card-text6-2": "Brend: GOODTECH",
        "button6-2": "Yaqinroq",
        "card-title-modal6-2": "GOODTECH kompressor",
        "card-text-modal6-2": "Brend: GOODTECH",
        center2_1: "Bizda",
        center2_2: "ishlab",
        center2_3: "chiqarilishi",
        center2_4: "kutilayotgan",
        center2_5: "mahsulotlar",
        "card-title4": "CHAMPION IW-180/8,4A mini",
        "card-text4": "Inverterli payvandlash mashinasi",
        "card-title-body4_1": "Quvvat",
        "card-title-body4_2": "manbai",
        "card-title-body4_3": "kuchlanishi",
        "card-title-body4_4": "220V",
        "card-title-body4_5": "Maks",
        "card-title-body4_6": "quvvat",
        "card-title-body4_7": "sarfi",
        "card-title-body4_8": "8.4kV",
        "card-title-body4_9": "Cos PH:",
        "card-title-body4_10": "0.7,",
        "card-title-body4_11": "elektrod",
        "card-title-body4_12": "diametri: 4mm",
        "card-title-body5_1": "6.6kV",
        "card-title-body5_2": "0.8,",
        "card-title-body5_3": "Payvandlash",
        "card-title-body5_4": "To'g'ridan-to'g'ri (DC)",
        "card-title5": "Bestweld Best 180",
        "card-text5": "Inverterli payvandlash mashinasi",
        "card-title6": "Kia EV6",
        "card-text6": "Narxi $42,115 dan",
        "card-title-body6": "2017 yilda GT-R yangilangan uslubni, yangi interyerni va asosiy dvigatel uchun 565 ot kuchiga ega bo'lgan zarbani, shuningdek transm ...",
        contact_p__1: "Bizning asosiy saytimizdan ham xabardor bo'ling",
        contact_p__2: "Goodtech => bu kompaniyamizning bir kichik sohasi hisoblanadi.",
        call_outline: "Biz bilan bog'lanish",
        offcanvas_header: "Biz bilan bog'lanish siz uchun qulay va oson",
        call_offcanvas__button1: "qo'ng'iroq qiling",
        call_offcanvas__button2: "qo'ng'iroq qiling",
        addres: "Manzil: Toshkent sh., Usta-Shirin 116/6, Jomiy bozori Ob'ekt yo'nalishi: 'Jomi' ",
        google: "Google xarita",
        yandex: "Yandex xarita",
        name_auto: "Payvandlash mashinalari",
        number_auto: "Aksessuarlar",
        price_auto: "ARC materiallari",
        footer_end: "© 2022 Goodtech PHOENIX TEAM tomonidan ishlab chiqilgan",
    },
    
    Ru: {
        nav_item1: "Дома",
        nav_item2: "Портфолио",
        nav_item3: "Блог",
        nav_item4: "Страницы",
        nav_item5: "Связь",
        animation1_1: "Всегда",
        animation1_2: "самые",
        animation1_3: "свежие ",
        animation1_4: "модели",
        animation1_5: "вы можете",
        big_contain: "Выгодные цены",
        animation2_1: "вы",
        animation2_2: "можете",
        animation2_3: "найти его",
        animation2_4: "по удобным",
        animation2_5: "доступным ценам",
        center1_1: "Вы",
        center1_2: "можете",
        center1_3: "купить",
        center1_4: "у нас",
        center1_5: "следующее",
        "card-title1": "Компрессор GOODTECH",
        "card-text1": "Бренд: GOODTECH",
        button1: "Ближе",
        "card-title-modal1": "Компрессор GOODTECH ",
        "card-text-modal1": "Бренд: GOODTECH",
        modal_nested1 : "Страна",
        modal_nested1_1 : "бренда:",
        modal_nested1_2 : "Китай,",
        modal_nested2 : "Напряжение:",
        modal_nested2_1 : "220В,",
        modal_nested2_1V : "380В",
        modal_nested3 : "Частота",
        modal_nested3_1 : "сети: 50 Гц,",
        modal_nested4 : "Поток:",
        modal_nested4_1 : "13.5 A,",
        modal_nested4_1A : "6.5 A",
        modal_nested4_1A_1 : "8.2 A",
        modal_nested4_1A_2 : "11 A",
        modal_nested5 : "Власть:",
        modal_nested5_1 : "2.2 кВ,",
        modal_nested5_1W : "3 кВ,",
        modal_nested5_1W_1 : "4 кВ,",
        modal_nested5_1W_2 : "5.5 кВ,",
        modal_nested6 : "Скорость",
        modal_nested6_1 : "вращения:",
        modal_nested6_2 : "1050р/мин,",
        modal_nested6_2T : "950р/мин,",
        modal_nested7 : "Рабочее давление:",
        modal_nested7_1 : "0.8 МПа,",
        modal_nested8 : "Производительность:",
        modal_nested8_1 : "0.25 м3/мин,",
        modal_nested8_1H : "0.36 м3/мин,",
        modal_nested8_1H_1 : "0.6 м3/мин,",
        modal_nested8_1H_2 : "0.67 м3/мин,",
        modal_nested9 : "Цилиндр:",
        modal_nested9_1 : "65x2,",
        modal_nested9_1B : "65x3,",
        modal_nested9_1B_1 : "90x2,",
        modal_nested9_1B_2 : "80x2,",
        modal_nested10 : "Емкость бака:",
        modal_nested10_1 : "90 л.",
        modal_nested10_1L : "150 л.",
        modal_nested10_1L_1 : "180 л.",
        "card-title2": "Компрессор GOODTECH",
        "card-text2": "Бренд: GOODTECH",
        button2: "Ближе",
        "card-title-modal2": "Компрессор GOODTECH",
        "card-text-modal2": "Бренд: GOODTECH", 
        "card-title3": "Компрессор GOODTECH",
        "card-text3": "Бренд: GOODTECH",
        button3: "Ближе",
        "card-title-modal3": "Компрессор GOODTECH",
        "card-text-modal3": "Бренд: GOODTECH",
        "card-title6-2": "Компрессор GOODTECH",
        "card-text6-2": "Бренд: GOODTECH",
        "button6-2": "Ближе",
        "card-title-modal6-2": "Компрессор GOODTECH",
        "card-text-modal6-2": "Бренд: GOODTECH",
        center2_1: "Продукция",
        center2_2: "которую",
        center2_3: "предполагается",
        center2_4: "производить в",
        center2_5: "нашей стране", 
        "card-title4": "CHAMPION IW-180/8,4A mini",
        "card-text4": "Аппарат сварочный инверторный",
        "card-title-body4_1": "Напряжение",
        "card-title-body4_2": "питания",
        "card-title-body4_3": "220",
        "card-title-body4_4": "В",
        "card-title-body4_5": "Макс",
        "card-title-body4_6": "потребляемая",
        "card-title-body4_7": "мощность",
        "card-title-body4_8": "8.4кВ",
        "card-title-body4_9": "Кос-PH:",
        "card-title-body4_10": "0.7,",
        "card-title-body4_11": "диаметр",
        "card-title-body4_12": "электрода 4мм",
        "card-title-body5_1": "6.6kV",
        "card-title-body5_2": "0.8,",
        "card-title-body5_3": "Тип",
        "card-title-body5_4": "Прямой (DC)",
        "card-title5": "Bestweld Best 180",
        "card-text5": "Аппарат сварочный инверторный",
        "card-title-body5": "Максимальная потребляемая мощность, кВт: 6,6, Cos PH: 0,8, Тип сварочного тока: Постоянный (постоянный), Диапазон сварочного тока, А: 5-180.",
        "card-title6": "Киа EV6",
        "card-text6": "Цена от 42,115$",
        "card-title-body6": "В 2017 году GT-R будет отличаться обновленным стилем, новым интерьером и 565-сильным ходом основного двигателя, а также трансмиссией...",
        contact_p__1: "Оставайтесь с нами и на нашем основном сайте",
        contact_p__2: "Goodtech => это небольшое направление нашей компании.",
        call_outline: "Свяжитесь с нами",
        offcanvas_header: "Связаться с нами для вас удобно и просто",
        call_offcanvas__button1: "позвонить",
        call_offcanvas__button2: "позвонить",
        addres: "Адрес: Ташкент, Уста-Ширин 116/6, Джами базар Ориентир: 'Джами' ",
        google: "Карта Google",
        yandex: "Яндекс карта",
        name_auto: "Сварочный аппараты",
        number_auto: "Аксессуары",
        price_auto: "АРК материалы",
        footer_end: "© 2022 Goodtech Задизайнено в PHOENIX TEAM",
    },
};


const langTogglerUz = document.getElementById("lang-uz");
const langTogglerRu = document.getElementById("lang-ru");

const changeLanguage = (language) => {
    const translation = translations[language];
    
    document.querySelectorAll('[translate="yes"]').forEach((el) => {
        const key = el.attributes.getNamedItem("translationKey").value;
        el.textContent = translation[key];
    });
};

langTogglerUz.addEventListener("click", () => changeLanguage("Uz"));
langTogglerRu.addEventListener("click", () => changeLanguage("Ru"));

$(document).on('click', '.langWrap a', function(){
    $(this).addClass('active').siblings().removeClass('active');
});


$(document).ready(function(){ 
    $("#carouselExampleCaptions").carousel({interval: 30000});
});

$(document).ready(function(){ 
    $("#carouselExampleCaptions2").carousel({interval: 20000});
});
